### PR TITLE
Made possible to get multiline input

### PR DESCRIPTION
**Pull request by Turilas83**

### CODE REVIEW

**Comment by sapajune** [comment]
- It's not obvious that one should end input using ctrl-d.
- Storing to var destroys linefeeds anyway.

**Comment by kompa3** [comment]
> * It's not obvious that one should end input using ctrl-d.
> * Storing to var destroys linefeeds anyway.

I agree that Ctrl+D should be eg. echoed as an instruction by the script.

I tested with storing to var and echoing - it seems to preserve linefeeds?

```
[pulssi@dev-centos ~]$ TEST=$(</dev/stdin)
abc
def
ghi
[pulssi@dev-centos ~]$ echo "$TEST"
abc
def
ghi
[pulssi@dev-centos ~]$ echo "$TEST" > testi
[pulssi@dev-centos ~]$ cat testi
abc
def
ghi
[pulssi@dev-centos ~]$ 
```

**Comment by kompa3** [comment]
BTW. Options are still set incorrectly (ZBX_TLSCAFILE and two others). They should contain the file paths and not the certs/keys themselves.

**Comment by sapajune** [comment]
Ok. So linefeeds are lost only if the variable reference is unquoted so that should be fine.

**Comment by sapajune** [comment]
I think script would be nicer to user if you don't need to input certificate/key/CA at all if existing one is acceptable (i.e. input is requested only after answering y to delete question).

**Pull request merged**
