### PR TITLE
removed extra lines

### PR DESCRIPTION
**Pull request by hkuusela**
What else ?

### CODE REVIEW

**Comment by kompa3** [comment]
See Teams discussion: zabbix-java-gateway and zabbix-snmptraps versions in compose file need to be updated too

**Review by Turilas83 — APPROVED** [review]

**Comment by kompa3** [comment]
zabbix-snmptraps, I guess it should be alpine-5.0-latest

**Comment by kompa3** [comment]
setup-psk.sh creates the PSK file, it could be the proper place to:
```
chown 1997:1995  "zabbix/enc/${PSK_FILE}"
chmod 0600  "zabbix/enc/${PSK_FILE}"
```

**Review by kompa3 — APPROVED** [review]

**Comment by DigJurppe** [comment]
create-proxy.sh file seems now to be rather useless. All it does is `docker-compose up --no-start`.

**Review by DigJurppe — APPROVED** [review]

**Pull request merged**
